spring:
  datasource:
    password: password
    username: username
    url: "jdbc:h2:file:./data/h2"
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
  h2:
    console:
      enabled: true
  mvc:
    log-request-details: true
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework:
        web: DEBUG

gv4:
  basePath: api.gv4.core
  specificPath:
    pingController: ${gv4.basePath}/ping
    subjectController: ${gv4.basePath}/subject



