spring:
  mvc:
    log-request-details: true
logging:
  level:
    org:
      springframework:
        web: TRACE

gv4:
  basePath: api.gv4.core
  specificPath:
    pingController: ${gv4.basePath}/ping


